apiVersion: v1
kind: Service
metadata:
  name: myapp-service-1
  namespace: sabari
spec:
  type: NodePort
  selector:
    name: myapp
    type: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
