apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: sabari
  labels:
    name: mypod
spec:
  containers:
    - name: frontend
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginxvol
  volumes:
    - name: nginxvol
      persistentVolumeClaim:
        claimName: myvolclaim
