apiVersion: v1
kind: Service
metadata:
  name: jenkinsservice
  namespace: sabari

spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080

  selector:
    name: jenkins
    type: server
