apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: sabari
  labels:
    name: jenkins
    type: server
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
  volumes:
    - name: jenkins-home
      hostPath:
        path: /var/jenkins_home
        type: Directory
